### ISSUE TITLE
Installation without poetry?

### ISSUE THREAD

**Issue by nesdnuma** [mmalecki/cq-queryabolt#1]
Hello,

Do you know another way to install the lib without poetry? I have installed CadQuery some time ago and I think it was with Conda or Miniconda.

Thank you in advance.

**Comment by gitterman** [comment]
I have the same issue. I installed cadquery with miniconda as described on https://cadquery.readthedocs.io.
Is there an easy way to add your nice package with conda?

**Comment by mmalecki** [comment]
Hey folks, sorry for the delay on this one, it simply slipped through the cracks. Taking a look now.

**Comment by mmalecki** [comment]
Okay, while I don't use Conda and don't have it installed, it appears this is actually a fully supported use-case. `<env>` being the name of your Conda environment for CadQuery, you should be able to do:

```
mamba install -n <env> cq-queryabolt==0.1.1
```

I suspect you should be able to just use it in your code afterwards. Let me know if it works for you! I'll keep this one open, I'd love a confirmation so that I can add this to the documentation.

I am basing this one a [StackOverflow answer](https://stackoverflow.com/questions/33680946/how-to-add-package-to-conda-environment-without-pip) and Mamba documentation.

**Comment by mmalecki** [comment]
Let me know if this doesn't work for y'all!
